export const recommendedNutrients = [
	"rec_beta_carotene",
	"rec_caffeine",
	"rec_calcium",
	"rec_carbohydrate",
	"rec_cholesterol",
	"rec_fat",
	"rec_fiber",
	"rec_folic_acid",
	"rec_iron",
	"rec_niacin",
	"rec_potassium",
	"rec_protein",
	"rec_riboflavin",
	"rec_sodium",
	"rec_sugars",
	"rec_thiamin",
	"rec_vitamin_a",
	"rec_vitamin_b12",
	"rec_vitamin_c",
	"rec_vitamin_d",
	"rec_vitamin_e",
	"rec_vitamin_k",
	"rec_zinc"
];

export const snakeCasedNutrients = [
	"beta_carotene",
	"caffeine",
	"calcium",
	"carbohydrate",
	"cholesterol",
	"fat",
	"fiber",
	"folic_acid",
	"iron",
	"niacin",
	"potassium",
	"protein",
	"riboflavin",
	"sodium",
	"sugars",
	"thiamin",
	"vitamin_a",
	"vitamin_b12",
	"vitamin_c",
	"vitamin_d",
	"vitamin_e",
	"vitamin_k",
	"zinc"
];

export const capitalizedNutrients = [
	"Beta Carotene",
	"Caffeine",
	"Calcium",
	"Carbohydrate",
	"Cholesterol",
	"Fat",
	"Fiber",
	"Folic Acid",
	"Iron",
	"Niacin",
	"Potassium",
	"Protein",
	"Riboflavin",
	"Sodium",
	"Sugars",
	"Thiamin",
	"Vitamin A",
	"Vitamin B12",
	"Vitamin C",
	"Vitamin D",
	"Vitamin E",
	"Vitamin K",
	"Zinc"
];
